# Generated by Django 6.0.7 on 2026-07-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperaturelog',
            name='sensor',
        ),
        migrations.AddField(
            model_name='temperaturelog',
            name='location',
            field=models.CharField(default='Terminal 1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperaturelog',
            name='sensor_id',
            field=models.CharField(default='T001', max_length=20),
            preserve_default=False,
        ),
    ]
